language: python
sudo: true
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

services:
  - mongodb

before_install:
  - export TZ=UTC

install:
  # Install all Python requirements (application and tests)
  - ./test/setup_test.sh
  # To help eventual debug: knowing which exact versions are in use can be rather useful.
  - pip freeze

script:
  # Code dynamic analysis and tests
  - cd test
  # Run test suite with py.test running its coverage plugin
  - pytest --verbose --durations=10 --no-print-logs --cov=alignak_module_logs --cov-config .coveragerc test_*.py
  # Report about coverage - Upload coverage results to codecov
  - bash <(curl -s https://codecov.io/bash)
  - cd ..
after_success:

jobs:
  include:
    - stage: Coding standard
      python: 3.6
      script:
        # Static code analysis
        # -- pycodestyle (former pep8)
        - pycodestyle --max-line-length=100 --exclude='*.pyc, *.cfg, *.log' --ignore='E402' --ignore='W504' alignak_module_logs/*
        # -- pylint
        - pylint --rcfile=.pylintrc -r no alignak_module_logs
        # -- pep257
        - pep257 --select=D300 alignak_module_logs
    - stage: Pypi deployment
      python: 3.6
      script: echo "Deploying to PyPi..."
      if: (tag IS present)
      deploy:
      - provider: pypi
        distributions: "sdist bdist_wheel"
        skip_existing: true
        on:
          tags: true
        user: alignak
        password:
          secure: "Q9S/ZyFULg5nOrIxQG+bYybBLhpcI5EIVZRn7xJrNlHfbrzSBmTsgYRKkh4AEA5cfiYUaA40rOShi641C2G3lbLGzTtipyxugA0kwBlk57Ot8KCNQucddvuMlM1zJl3+flR2aDlnpq9XDgmm9wzVTWt3LaeDDrXqNUxVwE9qfYlzVS5bbdHYx1TI2y1iEBwNCydGZNXi3vSkrqk3SqWfX07PAawgincAq2RlD3c8VfjcGf1JTm57TWQ6zvrf682dKC2nzGBzvNMzqLgsFwCB6vQwcIROAniE6bO67KtGA4ZtqDnaXiwM7lAD/oatILFzzg92pg5TyUdUeEdl3fTVQyDyCkOG6oNCvyMAZz0e37CRGMjtY1+lvdNJwvWydwEtfGaYb+2RmxX8q5hZyHSX7v1aQ5m1S3fQ4bXcJ+TeATU9oj+PtrR+O+5n/HpG9PYf+xgTzx9L7KKAK2kjYcChbY7MuXLLODHuX3PRGR6tD0uEJvdpNGw6EbJGm6/fQorWNmVyk0eT9fMHBK8BQsRqtzYUKONImLzzuQhVJifL1CzdpQV8v36HX9mNKtZdOGNCVzlY345P5ng9iO+XzTX+78xw2aTN9NgGifAKaGj3ZzCJRzVyqm1LBfGnfLP4tMlHvwOFzCu738TGlVPYFtekDV73eRB8zIeElrXjKx7SY8A="
    - stage: Debian packaging - Python 2
      python: 2.7
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
        - pip install -r requirements.txt
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-deb.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "QnFV5CaQtAkDHymNf9O5L0Vs00V7omGT2TQCQl3V8SnA+vF7jrplYVsPGhOCqVGVthByyCeR5/Sh9fbJ3CMXkQ0KVbGsb4zKArzuqD/8pkeqQCg+bavOnM8TPg96h46bcvX5B9q/1hl171snu3TL/SXVpd/UPv92Q4c++XaZEa8tTTaviMMPh5Yw3M9t+ZMPM4F5aBZ64KwOPgMRGNaS80XMpRG7RjZcLyxsviolwFbFeSfUpiKRSzAXR8SGvaGTZOlH9iCGLWnurobTuQor2LDyoh4P/DPWRyOsckQWcwdNe3qD34kXUccfY74ChVhpqbKKSRugCvPP3JQHLxWzPhqF2PiIKea9ugOGXaykN6XgQ+yqdIfMsSDgE+LBN07uEz+lT3Vqs0b4KLqu7obGERhcK1Fqb6rj7ijQbbc2BBr3Oxew3sldkZwUcyrEuYNCZ0XCSNXC41yh0lr9yDaljXrIDuJB6xOv1HellPG7HdECjMB8Slknr/B7aPCdvHYdRFvKd8xky3lOn5lqeI7nfYHQQ0L/mv7qfkW6M+OgxmUY/udreyQIz4Qd2XtWxcag9jjBLNIx16tFmb7rM6ucybzZLay9RbJetcgSO92qoNO/ShmBNB1rOStqmEXEVBGSvueLBVuei7IEhUMKXX5A1swaVXisnHIQ3CmilpMEAXs="
    - stage: Debian packaging - Python 3
      python: 3.6
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION deb
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-deb.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "QnFV5CaQtAkDHymNf9O5L0Vs00V7omGT2TQCQl3V8SnA+vF7jrplYVsPGhOCqVGVthByyCeR5/Sh9fbJ3CMXkQ0KVbGsb4zKArzuqD/8pkeqQCg+bavOnM8TPg96h46bcvX5B9q/1hl171snu3TL/SXVpd/UPv92Q4c++XaZEa8tTTaviMMPh5Yw3M9t+ZMPM4F5aBZ64KwOPgMRGNaS80XMpRG7RjZcLyxsviolwFbFeSfUpiKRSzAXR8SGvaGTZOlH9iCGLWnurobTuQor2LDyoh4P/DPWRyOsckQWcwdNe3qD34kXUccfY74ChVhpqbKKSRugCvPP3JQHLxWzPhqF2PiIKea9ugOGXaykN6XgQ+yqdIfMsSDgE+LBN07uEz+lT3Vqs0b4KLqu7obGERhcK1Fqb6rj7ijQbbc2BBr3Oxew3sldkZwUcyrEuYNCZ0XCSNXC41yh0lr9yDaljXrIDuJB6xOv1HellPG7HdECjMB8Slknr/B7aPCdvHYdRFvKd8xky3lOn5lqeI7nfYHQQ0L/mv7qfkW6M+OgxmUY/udreyQIz4Qd2XtWxcag9jjBLNIx16tFmb7rM6ucybzZLay9RbJetcgSO92qoNO/ShmBNB1rOStqmEXEVBGSvueLBVuei7IEhUMKXX5A1swaVXisnHIQ3CmilpMEAXs="
    - stage: RPM packaging - Python 2
      python: 2.7
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
        - sudo apt-get install -y rpm
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-rpm.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "QnFV5CaQtAkDHymNf9O5L0Vs00V7omGT2TQCQl3V8SnA+vF7jrplYVsPGhOCqVGVthByyCeR5/Sh9fbJ3CMXkQ0KVbGsb4zKArzuqD/8pkeqQCg+bavOnM8TPg96h46bcvX5B9q/1hl171snu3TL/SXVpd/UPv92Q4c++XaZEa8tTTaviMMPh5Yw3M9t+ZMPM4F5aBZ64KwOPgMRGNaS80XMpRG7RjZcLyxsviolwFbFeSfUpiKRSzAXR8SGvaGTZOlH9iCGLWnurobTuQor2LDyoh4P/DPWRyOsckQWcwdNe3qD34kXUccfY74ChVhpqbKKSRugCvPP3JQHLxWzPhqF2PiIKea9ugOGXaykN6XgQ+yqdIfMsSDgE+LBN07uEz+lT3Vqs0b4KLqu7obGERhcK1Fqb6rj7ijQbbc2BBr3Oxew3sldkZwUcyrEuYNCZ0XCSNXC41yh0lr9yDaljXrIDuJB6xOv1HellPG7HdECjMB8Slknr/B7aPCdvHYdRFvKd8xky3lOn5lqeI7nfYHQQ0L/mv7qfkW6M+OgxmUY/udreyQIz4Qd2XtWxcag9jjBLNIx16tFmb7rM6ucybzZLay9RbJetcgSO92qoNO/ShmBNB1rOStqmEXEVBGSvueLBVuei7IEhUMKXX5A1swaVXisnHIQ3CmilpMEAXs="
    - stage: RPM packaging - Python 3
      python: 3.6
      if: (tag IS blank)
      install:
        # Install packaging requirements
        - echo "Installing packaging requirements..."
        - sudo apt-get install -y rpm
      script:
        - echo "Packaging for BinTray..."
        - ./package.sh $TRAVIS_BRANCH $TRAVIS_PYTHON_VERSION rpm
      deploy:
      - provider: bintray
        skip_cleanup: true
        file: dist/.bintray-rpm.json
        on:
          all_branches: true
        user: mohierf
        key:
          secure: "QnFV5CaQtAkDHymNf9O5L0Vs00V7omGT2TQCQl3V8SnA+vF7jrplYVsPGhOCqVGVthByyCeR5/Sh9fbJ3CMXkQ0KVbGsb4zKArzuqD/8pkeqQCg+bavOnM8TPg96h46bcvX5B9q/1hl171snu3TL/SXVpd/UPv92Q4c++XaZEa8tTTaviMMPh5Yw3M9t+ZMPM4F5aBZ64KwOPgMRGNaS80XMpRG7RjZcLyxsviolwFbFeSfUpiKRSzAXR8SGvaGTZOlH9iCGLWnurobTuQor2LDyoh4P/DPWRyOsckQWcwdNe3qD34kXUccfY74ChVhpqbKKSRugCvPP3JQHLxWzPhqF2PiIKea9ugOGXaykN6XgQ+yqdIfMsSDgE+LBN07uEz+lT3Vqs0b4KLqu7obGERhcK1Fqb6rj7ijQbbc2BBr3Oxew3sldkZwUcyrEuYNCZ0XCSNXC41yh0lr9yDaljXrIDuJB6xOv1HellPG7HdECjMB8Slknr/B7aPCdvHYdRFvKd8xky3lOn5lqeI7nfYHQQ0L/mv7qfkW6M+OgxmUY/udreyQIz4Qd2XtWxcag9jjBLNIx16tFmb7rM6ucybzZLay9RbJetcgSO92qoNO/ShmBNB1rOStqmEXEVBGSvueLBVuei7IEhUMKXX5A1swaVXisnHIQ3CmilpMEAXs="
